PAGINAS = {}

PAGINAS["s1"] = dict(
    ruta="semana-01/index.html", fragmento="s1.html", raiz="../", semana="s1",
    title="Semana 1 · R como herramienta para pensar",
    description="Guía de estudio FPEN, semana 1: consola y scripts, objetos y asignación, tipos de datos, operadores, funciones y vectores en R, con casos de economía y negocios.",
    num="01", sr="Semana 1", mod="Unidad 1 · R como herramienta para pensar con datos",
    h1="¿Qué puedo hacer con R y cómo le doy instrucciones?",
    lead="Antes de analizar un solo dato económico, R necesita que aprendas a hablarle: crear objetos, hacer cálculos y usar funciones. Esta guía cubre exactamente eso, y solo eso: nada de <code>dplyr</code> ni <code>ggplot2</code> todavía.",
    pregunta="¿Cómo le doy a R instrucciones precisas para calcular ingresos, costos y crecimientos, y cómo sé que el resultado es correcto?",
    meta=[("Lectura", "R4DS cap. 2 · Workflow: basics"), ("Proyecto", "Fase 1: equipos, tema y datos"), ("!Evaluación", "Control 01: semanas 1 a 3")],
    ciclo=[],
    toc_titulo="Semana 1",
    toc=["Antes de clase", ("uso", "Cómo usar la guía"), ("mapa", "Qué puedes usar"), ("lecturas", "Lecturas"), ("checkpoint", "Control de lectura"),
         "Aprender", ("consola", "Consola y scripts"), ("objetos", "Objetos y asignación"), ("tipos", "Tipos de datos"), ("operadores", "Operadores"),
         ("funciones", "Funciones y argumentos"), ("vectores", "Vectores"), ("ayuda", "Ayuda y errores"),
         "Practicar", ("trazas", "Tablas de traza"), ("ejercicios", "Ejercicios"), ("playground", "Playground"), ("practica", "Práctica intensiva"),
         "Proyecto y evaluación", ("proyecto", "Proyecto: Fase 1"), ("evaluacion", "Rumbo al Control 01"), ("cheat", "Cheat sheet"), ("fuentes", "Fuentes")],
)

PAGINAS["s5"] = dict(
    ruta="semana-05/index.html", fragmento="s5.html", raiz="../", semana="s5",
    title="Semana 5 · El pipe y los verbos de transformación",
    description="Guía de estudio FPEN, semana 5, sesión 1: el operador pipe nativo |>, filter() con Y, O y %in%, arrange(), select() y rename() con nycflights13 y datos de ventas.",
    num="05", sr="Semana 5", mod="Resumir, comparar e interpretar · Sesión 1 (21 de septiembre)",
    h1="El operador pipe en acción: repasando los verbos antes de agrupar",
    lead="Esta sesión retoma <strong>filter()</strong>, <strong>arrange()</strong>, <strong>select()</strong> y <strong>rename()</strong>, ya vistos en la semana 4, pero ahora con la mecánica completa del pipe <code>|&gt;</code>, la diferencia entre <strong>Y</strong> y <strong>O</strong> y el uso de <code>%in%</code>.",
    pregunta="¿Cómo convierto miles de observaciones en la tabla exacta que necesito para responder una pregunta?",
    meta=[("Lectura", "R4DS cap. 3, §3.2–3.4 (repaso)"), ("Proyecto", "Base lista para resumir"), ("!Evaluación", "Primer Parcial: semana 6")],
    ciclo=["transformar"],
    toc_titulo="Semana 5 · Sesión 1",
    toc=["Antes de clase", ("uso", "Cómo usar la guía"), ("mapa", "Qué puedes usar"), ("lecturas", "Lecturas"), ("checkpoint", "Control de lectura"),
         "Aprender", ("por-que", "Los datos no llegan listos"), ("funciones", "Funciones: repaso"), ("pipe", "El pipe |>"), ("filter", "filter()"),
         ("arrange", "arrange()"), ("select", "select() y rename()"), ("aplicacion", "Con datos de tu carrera"),
         "Practicar", ("trazas", "Tabla de traza"), ("ejercicios", "Ejercicios"), ("playground", "Playground"), ("practica", "Práctica intensiva"),
         "Proyecto y evaluación", ("proyecto", "Proyecto"), ("evaluacion", "Rumbo al Parcial"), ("cheat", "Cheat sheet"), ("fuentes", "Fuentes")],
)

PAGINAS["s2"] = dict(
    ruta="semana-02/index.html", fragmento="s2.html", raiz="../", semana="s2",
    title="Semana 2 · De valores a conjuntos de datos",
    description="Guía de estudio FPEN, semana 2: operaciones vectorizadas, indexación, vectores lógicos, matrices, data frames e importación de CSV con readr, con datos de hogares y ventas.",
    num="02", sr="Semana 2", mod="Unidad 2 · De valores individuales a conjuntos de datos",
    h1="¿Cómo representa R los datos con los que trabaja un economista?",
    lead="De un número suelto a una serie, de una serie a una tabla y de un archivo a un objeto de R. Esta semana aprendes a recortar vectores, a leer una tabla por filas y columnas y a importar una base sin creerle a ciegas.",
    pregunta="¿Qué representa cada fila y cada columna de mi base, y cómo sé que R la leyó bien antes de calcular nada?",
    meta=[("Lectura", "R4DS cap. 7, §7.2 · Data import"), ("Proyecto", "Fase 2: conocer la base"), ("!Evaluación", "Control 01: semanas 1 a 3")],
    ciclo=["importar"],
    toc_titulo="Semana 2",
    toc=["Antes de clase", ("uso", "Cómo usar la guía"), ("mapa", "Qué puedes usar"), ("lecturas", "Lecturas"), ("checkpoint", "Control de lectura"),
         "Aprender", ("vectorizadas", "Vectorización y reciclaje"), ("indexar", "Indexar"), ("logicos", "Vectores lógicos"), ("tipos-vector", "Un vector, un tipo"),
         ("matrices", "Matrices"), ("data-frames", "Data frames"), ("importar", "Importar un CSV"),
         "Practicar", ("trazas", "Tablas de traza"), ("ejercicios", "Ejercicios"), ("practica", "Práctica intensiva"),
         "Proyecto y evaluación", ("proyecto", "Proyecto: Fase 2"), ("evaluacion", "Rumbo al Control 01"), ("cheat", "Cheat sheet"), ("fuentes", "Fuentes")],
)

PAGINAS["s3"] = dict(
    ruta="semana-03/index.html", fragmento="s3.html", raiz="../", semana="s3",
    title="Semana 3 · Visualizar antes de modelar",
    description="Guía de estudio FPEN, semana 3: ggplot2 con data, aes y geom; barras, histograma, boxplot, dispersión y líneas; estéticas, facetas y cómo elegir el gráfico según la pregunta.",
    num="03", sr="Semana 3", mod="Unidad 3 · Visualizar antes de modelar",
    h1="¿Qué puedo descubrir de mis datos antes de calcular?",
    lead="Un buen gráfico muestra en segundos lo que una tabla esconde: dónde se concentran los salarios, qué grupo está mejor, si dos variables se mueven juntas. Esta semana aprendes la gramática de <code>ggplot2</code> y, sobre todo, a elegir el gráfico que responde tu pregunta.",
    pregunta="¿Qué gráfico responde mi pregunta, y qué puedo afirmar (y qué no) a partir de él?",
    meta=[("Lectura", "R4DS cap. 1 · Data visualization"), ("Proyecto", "Fases 3–4: primeras visualizaciones"), ("!Evaluación", "Control 01: semanas 1 a 3")],
    ciclo=["visualizar"],
    toc_titulo="Semana 3",
    toc=["Antes de clase", ("uso", "Cómo usar la guía"), ("mapa", "Qué puedes usar"), ("lecturas", "Lecturas"), ("checkpoint", "Control de lectura"),
         "Aprender", ("gramatica", "La gramática"), ("una-variable", "Una variable"), ("comparar", "Comparar grupos"), ("relaciones", "Relaciones y estéticas"),
         ("tiempo", "Evolución en el tiempo"), ("elegir", "Elegir el gráfico"),
         "Practicar", ("trazas", "Traza de gráficos"), ("ejercicios", "Ejercicios"), ("practica", "Práctica intensiva"),
         "Proyecto y evaluación", ("proyecto", "Proyecto: Fases 3–4"), ("evaluacion", "Rumbo al Control 01"), ("cheat", "Cheat sheet"), ("fuentes", "Fuentes")],
)

PAGINAS["s4"] = dict(
    ruta="semana-04/index.html", fragmento="s4.html", raiz="../", semana="s4",
    title="Semana 4 · Transformar datos para responder preguntas",
    description="Guía de estudio FPEN, semana 4: dplyr formal con select, filter, arrange y mutate, el pipe nativo, operadores relacionales y lógicos, y valores faltantes con is.na y na.rm.",
    num="04", sr="Semana 4", mod="Unidad 4 · Transformar datos para responder preguntas",
    h1="Tengo una base. ¿Cómo obtengo la información que necesito?",
    lead="Una base original casi nunca responde la pregunta tal como llega. Esta semana aprendes a quedarte con la subpoblación correcta, a crear las variables que el análisis necesita (crecimiento, margen, salario real) y a no dejar que un valor faltante arruine un promedio.",
    pregunta="¿Qué filas, qué columnas y qué variables nuevas necesito para responder mi pregunta, y qué hago con los datos que faltan?",
    meta=[("Lectura", "R4DS cap. 3 y selecciones del cap. 12"), ("Proyecto", "Fases 3–4: preparación de datos"), ("!Evaluación", "Primer Parcial: semana 6")],
    ciclo=["transformar"],
    toc_titulo="Semana 4",
    toc=["Antes de clase", ("uso", "Cómo usar la guía"), ("mapa", "Qué puedes usar"), ("lecturas", "Lecturas"), ("checkpoint", "Control de lectura"),
         "Aprender", ("dplyr", "Verbos de dplyr"), ("pipe", "El pipe |>"), ("filter", "Filtrar subpoblaciones"), ("mutate", "Crear variables"), ("na", "Valores faltantes"),
         "Practicar", ("trazas", "Tablas de traza"), ("ejercicios", "Ejercicios"), ("practica", "Práctica intensiva"),
         "Proyecto y evaluación", ("proyecto", "Proyecto"), ("evaluacion", "Rumbo al Parcial"), ("cheat", "Cheat sheet"), ("fuentes", "Fuentes")],
)

PAGINAS["c1g"] = dict(
    ruta="control-01/guia/index.html", fragmento="c1g.html", raiz="../../", semana="c1", progreso="c1g",
    title="Control 01 · Guía de lectura y análisis",
    description="Guía de lectura profunda del Control 01 de FPEN: R como herramienta para pensar, cómo representa R los datos y visualización con ggplot2, con 36 preguntas para analizar y R4DS en contexto.",
    num="C1", sr="Control 01", mod="Semanas 1 a 3 · Guía de lectura profunda",
    h1="Guía de lectura profunda y análisis para el Control 01",
    lead="Para leer con calma, no para cronometrar: los conceptos de las tres primeras semanas con analogías económicas, código de R que puedes ejecutar y 36 preguntas para razonar por escrito antes de ver el análisis.",
    pregunta="¿Puedo explicar, para cualquier resultado que produzca con R, cómo sé que es correcto?",
    meta=[("Lecturas", "R4DS cap. 2, cap. 7 (§7.2) y cap. 1"), ("Temario", "Semanas 1 a 3"), ("!Evaluación", "Control 01 · Sin IA")],
    ciclo=["importar", "ordenar", "transformar", "visualizar"],
    toc_titulo="Control 01 · Guía",
    toc=["Empezar", ("uso", "Cómo usar la guía"), ("checkpoint", "Autoevaluación rápida"),
         "Lectura profunda", ("unidad-1", "1 · R para pensar"), ("unidad-2", "2 · Cómo representa R los datos"), ("unidad-3", "3 · Visualizar"),
         "36 preguntas", ("p-pensar", "01 · Pensar antes de programar"), ("p-instrucciones", "02 · R y las instrucciones"), ("p-vectores", "03 · Vectores y condiciones"),
         ("p-estructura", "04 · Estructura y verificación"), ("p-visualizar", "05 · Visualizar e interpretar"),
         "Cierre", ("r4ds", "R4DS en contexto"), ("mapa-cierre", "Mapa y cierre"), ("evaluacion", "Lista “puedo…”"), ("fuentes", "Fuentes")],
)

PAGINAS["c1r"] = dict(
    ruta="control-01/repaso/index.html", fragmento="c1r.html", raiz="../../", semana="c1", progreso="c1r",
    title="Control 01 · Repaso y simulacro",
    description="Repaso integrador del Control 01 de FPEN: 30 preguntas de teoría, práctica con R en vivo (webR) sobre un caso de puntos de venta, simulacro cronometrado de 45 minutos y cheat sheet.",
    num="C1", sr="Control 01", mod="Semanas 1 a 3 · Repaso integrador y simulacro",
    h1="Repaso integrador y simulacro del Control 01",
    lead="Teoría con respuesta escrita, práctica con R real en tu navegador sobre un caso de ventas en un campus, un simulacro de 45 minutos con las respuestas cerradas hasta el final y un cheat sheet de una pantalla.",
    pregunta="¿Puedo resolver, sin ayuda de IA, un problema con datos de principio a fin y justificar por qué confío en el resultado?",
    meta=[("Lecturas", "R4DS cap. 2, cap. 7 (§7.2) y cap. 1"), ("R en vivo", "webR en el navegador"), ("!Evaluación", "Control 01 · Sin IA")],
    ciclo=["importar", "ordenar", "transformar", "visualizar"],
    toc_titulo="Control 01 · Repaso",
    toc=["Empezar", ("uso", "Cómo usar el repaso"),
         "Teoría", ("t-pensar", "01 · Pensar antes de programar"), ("t-instrucciones", "02 · R y las instrucciones"), ("t-vectores", "03 · Vectores y condiciones"),
         ("t-estructura", "04 · Estructura y verificación"), ("t-visualizar", "05 · Visualizar e interpretar"),
         "Practicar", ("practica-r", "Práctica con R"), ("simulacro", "Simulacro (45 min)"),
         "Cierre", ("cheat", "Cheat sheet"), ("fuentes", "Fuentes")],
)

PAGINAS["index"] = dict(
    ruta="index.html", fragmento="index.html", raiz="", portada=True, codigo=False, momentos=False, tramos=[2, 3, 4],
    toc_titulo="Inicio", toc=["La guía", ("recorrido", "Del código a una decisión"), ("temario", "Temario"),
                              "Cómo estudiar", ("uso", "Cómo estudiar con esta guía"),
                              "El curso", ("evaluacion", "Evaluación"), ("bibliografia", "Bibliografía"), ("progreso", "Tu progreso")],
    title="Guía de estudio FPEN",
    description="Guía de estudio interactiva de Fundamentos de Programación para Economía y Negocios (ESEN, ciclo III/2026): R y el Tidyverse semana a semana, con R ejecutable en la página, quizzes, trazas y práctica tipo examen.",
)
